//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_2_DAS_2021.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cine_DAS2021Entities : DbContext
    {
        public Cine_DAS2021Entities()
            : base("name=Cine_DAS2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pelicula> peliculas { get; set; }

        public System.Data.Entity.DbSet<Desafio_2_DAS_2021.Models.PeliculasCLS> PeliculasCLS { get; set; }
    }
}
