//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_2_DAS_2021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula
    {
        public int id_pelicula { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string director { get; set; }
        public string poster_name { get; set; }
        public byte[] poster { get; set; }
        public Nullable<int> puntuacion { get; set; }
    }
}
